repos:
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: trailing-whitespace
      - id: flake8

  - repo: local
    hooks:
      - id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: python3 -m pytest
        language: system
        pass_filenames: false
        always_run: true
